/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Relevance Backend
 * API documentation for the Relevance backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  PreFetchDto,
  PreFetchResponseDto
} from '../../model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Accepts hash, filetype and source type, allocates a server-side session and returns connectionId.
 * @summary Prepare for fetching and allocate a WebSocket connectionId
 */
export type appBuilderControllerPreFetchResponse200 = {
  data: PreFetchResponseDto
  status: 200
}
    
export type appBuilderControllerPreFetchResponseSuccess = (appBuilderControllerPreFetchResponse200) & {
  headers: Headers;
};
;

export type appBuilderControllerPreFetchResponse = (appBuilderControllerPreFetchResponseSuccess)

export const getAppBuilderControllerPreFetchUrl = () => {


  

  return `/app-builder/pre-fetch`
}

export const appBuilderControllerPreFetch = async (preFetchDto: PreFetchDto, options?: RequestInit): Promise<appBuilderControllerPreFetchResponse> => {
  
  return customInstance<appBuilderControllerPreFetchResponse>(getAppBuilderControllerPreFetchUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      preFetchDto,)
  }
);}




export const getAppBuilderControllerPreFetchMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof appBuilderControllerPreFetch>>, TError,{data: PreFetchDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof appBuilderControllerPreFetch>>, TError,{data: PreFetchDto}, TContext> => {

const mutationKey = ['appBuilderControllerPreFetch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof appBuilderControllerPreFetch>>, {data: PreFetchDto}> = (props) => {
          const {data} = props ?? {};

          return  appBuilderControllerPreFetch(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AppBuilderControllerPreFetchMutationResult = NonNullable<Awaited<ReturnType<typeof appBuilderControllerPreFetch>>>
    export type AppBuilderControllerPreFetchMutationBody = PreFetchDto
    export type AppBuilderControllerPreFetchMutationError = unknown

    /**
 * @summary Prepare for fetching and allocate a WebSocket connectionId
 */
export const useAppBuilderControllerPreFetch = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof appBuilderControllerPreFetch>>, TError,{data: PreFetchDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof appBuilderControllerPreFetch>>,
        TError,
        {data: PreFetchDto},
        TContext
      > => {

      const mutationOptions = getAppBuilderControllerPreFetchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    