/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Relevance Backend
 * API documentation for the Relevance backend
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  PreUploadDto,
  PreUploadResponseDto
} from '../../model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Accepts hash and filetype, allocates a server-side session and returns connectionId.
 * @summary Prepare for upload and allocate a WebSocket connectionId
 */
export type appBuilderControllerPreUploadResponse200 = {
  data: PreUploadResponseDto
  status: 200
}
    
export type appBuilderControllerPreUploadResponseSuccess = (appBuilderControllerPreUploadResponse200) & {
  headers: Headers;
};
;

export type appBuilderControllerPreUploadResponse = (appBuilderControllerPreUploadResponseSuccess)

export const getAppBuilderControllerPreUploadUrl = () => {


  

  return `/app-builder/pre-upload`
}

export const appBuilderControllerPreUpload = async (preUploadDto: PreUploadDto, options?: RequestInit): Promise<appBuilderControllerPreUploadResponse> => {
  
  return customInstance<appBuilderControllerPreUploadResponse>(getAppBuilderControllerPreUploadUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      preUploadDto,)
  }
);}




export const getAppBuilderControllerPreUploadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof appBuilderControllerPreUpload>>, TError,{data: PreUploadDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof appBuilderControllerPreUpload>>, TError,{data: PreUploadDto}, TContext> => {

const mutationKey = ['appBuilderControllerPreUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof appBuilderControllerPreUpload>>, {data: PreUploadDto}> = (props) => {
          const {data} = props ?? {};

          return  appBuilderControllerPreUpload(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AppBuilderControllerPreUploadMutationResult = NonNullable<Awaited<ReturnType<typeof appBuilderControllerPreUpload>>>
    export type AppBuilderControllerPreUploadMutationBody = PreUploadDto
    export type AppBuilderControllerPreUploadMutationError = unknown

    /**
 * @summary Prepare for upload and allocate a WebSocket connectionId
 */
export const useAppBuilderControllerPreUpload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof appBuilderControllerPreUpload>>, TError,{data: PreUploadDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof appBuilderControllerPreUpload>>,
        TError,
        {data: PreUploadDto},
        TContext
      > => {

      const mutationOptions = getAppBuilderControllerPreUploadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    