/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Relevance Backend
 * API documentation for the Relevance backend
 * OpenAPI spec version: 1.0
 */

export * from './preFetchDto';
export * from './preFetchDtoType';
export * from './preFetchResponseDto';
export * from './preFetchUploadApkBodyDto';
export * from './preFetchUploadApkBodyDtoFiletype';