/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Relevance Backend
 * API documentation for the Relevance backend
 * OpenAPI spec version: 1.0
 */

/**
 * File type identifier
 */
export type PreFetchUploadApkBodyDtoFiletype = typeof PreFetchUploadApkBodyDtoFiletype[keyof typeof PreFetchUploadApkBodyDtoFiletype];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreFetchUploadApkBodyDtoFiletype = {
  apk: 'apk',
  xapk: 'xapk',
  apks: 'apks',
} as const;
