/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Relevance Backend
 * API documentation for the Relevance backend
 * OpenAPI spec version: 1.0
 */

export interface PreFetchResponseDto {
  /** Allocated WebSocket connection identifier */
  connectionId: string;
}
