/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Relevance Backend
 * API documentation for the Relevance backend
 * OpenAPI spec version: 1.0
 */
import type { PreFetchDtoType } from './preFetchDtoType';
import type { PreFetchUploadApkBodyDto } from './preFetchUploadApkBodyDto';

export interface PreFetchDto {
  /** APK source type */
  type: PreFetchDtoType;
  /** Request body for upload-apk type */
  body?: PreFetchUploadApkBodyDto;
}
