/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Relevance Backend
 * API documentation for the Relevance backend
 * OpenAPI spec version: 1.0
 */

/**
 * APK source type
 */
export type PreFetchDtoType = typeof PreFetchDtoType[keyof typeof PreFetchDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreFetchDtoType = {
  'upload-apk': 'upload-apk',
  apkpure: 'apkpure',
  'download-from-url': 'download-from-url',
  'google-play': 'google-play',
} as const;
