/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Relevance Backend
 * API documentation for the Relevance backend
 * OpenAPI spec version: 1.0
 */
import type { PreUploadDtoFiletype } from './preUploadDtoFiletype';

export interface PreUploadDto {
  /**
   * SHA-256 hex hash of the file
   * @minLength 64
   * @maxLength 64
   */
  hash: string;
  /** File type identifier */
  filetype: PreUploadDtoFiletype;
}
