/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddIndexRouteImport } from './routes/add/index'
import { Route as AddUploadConnectionIdRouteImport } from './routes/add/upload.$connectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddIndexRoute = AddIndexRouteImport.update({
  id: '/add/',
  path: '/add/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddUploadConnectionIdRoute = AddUploadConnectionIdRouteImport.update({
  id: '/add/upload/$connectionId',
  path: '/add/upload/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddIndexRoute
  '/add/upload/$connectionId': typeof AddUploadConnectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddIndexRoute
  '/add/upload/$connectionId': typeof AddUploadConnectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add/': typeof AddIndexRoute
  '/add/upload/$connectionId': typeof AddUploadConnectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add' | '/add/upload/$connectionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add' | '/add/upload/$connectionId'
  id: '__root__' | '/' | '/add/' | '/add/upload/$connectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddIndexRoute: typeof AddIndexRoute
  AddUploadConnectionIdRoute: typeof AddUploadConnectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/': {
      id: '/add/'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/upload/$connectionId': {
      id: '/add/upload/$connectionId'
      path: '/add/upload/$connectionId'
      fullPath: '/add/upload/$connectionId'
      preLoaderRoute: typeof AddUploadConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddIndexRoute: AddIndexRoute,
  AddUploadConnectionIdRoute: AddUploadConnectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
