/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddIndexRouteImport } from './routes/add/index'
import { Route as AddConnectionIdRouteImport } from './routes/add/$connectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddIndexRoute = AddIndexRouteImport.update({
  id: '/add/',
  path: '/add/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddConnectionIdRoute = AddConnectionIdRouteImport.update({
  id: '/add/$connectionId',
  path: '/add/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add/$connectionId': typeof AddConnectionIdRoute
  '/add': typeof AddIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add/$connectionId': typeof AddConnectionIdRoute
  '/add': typeof AddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add/$connectionId': typeof AddConnectionIdRoute
  '/add/': typeof AddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add/$connectionId' | '/add'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add/$connectionId' | '/add'
  id: '__root__' | '/' | '/add/$connectionId' | '/add/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddConnectionIdRoute: typeof AddConnectionIdRoute
  AddIndexRoute: typeof AddIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/': {
      id: '/add/'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/$connectionId': {
      id: '/add/$connectionId'
      path: '/add/$connectionId'
      fullPath: '/add/$connectionId'
      preLoaderRoute: typeof AddConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddConnectionIdRoute: AddConnectionIdRoute,
  AddIndexRoute: AddIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
